require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoooooooksController do

  # This should return the minimal set of attributes required to create a valid
  # Boooooook. As you add validations to Boooooook, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoooooooksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all boooooooks as @boooooooks" do
      boooooook = Boooooook.create! valid_attributes
      get :index, {}, valid_session
      assigns(:boooooooks).should eq([boooooook])
    end
  end

  describe "GET show" do
    it "assigns the requested boooooook as @boooooook" do
      boooooook = Boooooook.create! valid_attributes
      get :show, {:id => boooooook.to_param}, valid_session
      assigns(:boooooook).should eq(boooooook)
    end
  end

  describe "GET new" do
    it "assigns a new boooooook as @boooooook" do
      get :new, {}, valid_session
      assigns(:boooooook).should be_a_new(Boooooook)
    end
  end

  describe "GET edit" do
    it "assigns the requested boooooook as @boooooook" do
      boooooook = Boooooook.create! valid_attributes
      get :edit, {:id => boooooook.to_param}, valid_session
      assigns(:boooooook).should eq(boooooook)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Boooooook" do
        expect {
          post :create, {:boooooook => valid_attributes}, valid_session
        }.to change(Boooooook, :count).by(1)
      end

      it "assigns a newly created boooooook as @boooooook" do
        post :create, {:boooooook => valid_attributes}, valid_session
        assigns(:boooooook).should be_a(Boooooook)
        assigns(:boooooook).should be_persisted
      end

      it "redirects to the created boooooook" do
        post :create, {:boooooook => valid_attributes}, valid_session
        response.should redirect_to(Boooooook.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boooooook as @boooooook" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boooooook.any_instance.stub(:save).and_return(false)
        post :create, {:boooooook => {}}, valid_session
        assigns(:boooooook).should be_a_new(Boooooook)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boooooook.any_instance.stub(:save).and_return(false)
        post :create, {:boooooook => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boooooook" do
        boooooook = Boooooook.create! valid_attributes
        # Assuming there are no other boooooooks in the database, this
        # specifies that the Boooooook created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Boooooook.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => boooooook.to_param, :boooooook => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested boooooook as @boooooook" do
        boooooook = Boooooook.create! valid_attributes
        put :update, {:id => boooooook.to_param, :boooooook => valid_attributes}, valid_session
        assigns(:boooooook).should eq(boooooook)
      end

      it "redirects to the boooooook" do
        boooooook = Boooooook.create! valid_attributes
        put :update, {:id => boooooook.to_param, :boooooook => valid_attributes}, valid_session
        response.should redirect_to(boooooook)
      end
    end

    describe "with invalid params" do
      it "assigns the boooooook as @boooooook" do
        boooooook = Boooooook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boooooook.any_instance.stub(:save).and_return(false)
        put :update, {:id => boooooook.to_param, :boooooook => {}}, valid_session
        assigns(:boooooook).should eq(boooooook)
      end

      it "re-renders the 'edit' template" do
        boooooook = Boooooook.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boooooook.any_instance.stub(:save).and_return(false)
        put :update, {:id => boooooook.to_param, :boooooook => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boooooook" do
      boooooook = Boooooook.create! valid_attributes
      expect {
        delete :destroy, {:id => boooooook.to_param}, valid_session
      }.to change(Boooooook, :count).by(-1)
    end

    it "redirects to the boooooooks list" do
      boooooook = Boooooook.create! valid_attributes
      delete :destroy, {:id => boooooook.to_param}, valid_session
      response.should redirect_to(boooooooks_url)
    end
  end

end
