require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DetailmemosController do

  # This should return the minimal set of attributes required to create a valid
  # Detailmemo. As you add validations to Detailmemo, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DetailmemosController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET new" do
    it "assigns a new detailmemo as @detailmemo" do
      get :new, {}, valid_session
      assigns(:detailmemo).should be_a_new(Detailmemo)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Detailmemo" do
        expect {
          post :create, {:detailmemo => valid_attributes}, valid_session
        }.to change(Detailmemo, :count).by(1)
      end

      it "assigns a newly created detailmemo as @detailmemo" do
        post :create, {:detailmemo => valid_attributes}, valid_session
        assigns(:detailmemo).should be_a(Detailmemo)
        assigns(:detailmemo).should be_persisted
      end

      it "redirects to the created detailmemo" do
        post :create, {:detailmemo => valid_attributes}, valid_session
        response.should redirect_to(Book)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved detailmemo as @detailmemo" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detailmemo.any_instance.stub(:save).and_return(false)
        post :create, {:detailmemo => {}}, valid_session
        assigns(:detailmemo).should be_a_new(Detailmemo)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Detailmemo.any_instance.stub(:save).and_return(false)
        post :create, {:detailmemo => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested detailmemo" do
      detailmemo = Detailmemo.create! valid_attributes
      expect {
        delete :destroy, {:id => detailmemo.to_param}, valid_session
      }.to change(Detailmemo, :count).by(-1)
    end

    it "redirects to the detailmemos list" do
      detailmemo = Detailmemo.create! valid_attributes
      delete :destroy, {:id => detailmemo.to_param}, valid_session
      response.should redirect_to(book_path(1))
    end
  end

end
